name: Bug report
description: File a bug report
labels: "type/bug"
body:
  - type: markdown
    attributes:
      value: |
        Before you continue reporting the bug, be sure that it is not already reported, see

        - https://github.com/totaldebug/zigqt/issues

        You can find latest version from here:
        - https://github.com/totaldebug/zigqt/release

  - type: textarea
    id: description
    attributes:
      label: The problem
      description: A description of what the bug is
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: A description of what you expected to happen
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce the behaviour
      description: Write the command you used to run it, what you did before and after
      placeholder: |
        1.
        2.
        3.
        ...
    validations:
      required: true

  - type: textarea
    id: traceback
    attributes:
      render: text
      label: Error trace / logs
      description: >
        A complete traceback of the error or content of log file.

        This will be automatically formatted into code, so no need for backticks.

  - type: textarea
    id: workarounds
    attributes:
      label: Workarounds
      description: Is there an existing workaround for this issue? Did you try downgrading? Try finding version that can be used as a workaround.

  - type: input
    id: version
    attributes:
      label: Version
      placeholder: eg. 1.0.0
    validations:
      required: true

  - type: input
    id: alpine
    attributes:
      label: Alpine Version
      placeholder: eg. 1.17.0
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Make sure to close your issue when it's solved! If you found the solution yourself please comment so that others benefit from it.
