contact_links:
  - name: 💬 Discussions
    url: https://github.com/totaldebug/zigqt/discussions/new?category=support
    about: Please use Discussions to ask for support. Bugs (application crashes, errors) needs to be reported as issues.
  - name: Discord
    url: https://discord.gg/6fmekudc8Q
    about: Please ask and answer questions here.
blank_issues_enabled: false
