# Zigbee2mqtt sample configuration

# MQTT settings
mqtt:
  # MQTT base topic for Zigbee2MQTT MQTT messages
  base_topic: zigbee2mqtt
  # MQTT server URL
  server: "mqtt://localhost:1883"
  # MQTT server authentication, uncomment if required:
  # user: my_user
  # password: my_password
serial:
  # Location of Zigbee adapter.
  port: /dev/ttyACM0
  # Adapter type (may not be needed), (zstack, deconz or ezsp)
  adapter: deconz
# Web interface
frontend: true
# enable home assistant integration
homeassistant: true


advanced:
  log_level: info
  log_output:
    - console
    - syslog
  log_directory: /var/log/zigbee2mqtt
  log_syslog:
    facility: daemon
    path: /dev/log
    protocol: unix
  # Zigbee network key for better security
  network_key: GENERATE
# The following file paths are relative to the datadir (/var/lib/zigbee2mqtt)
devices: devices.yaml
groups: groups.yaml
